### ISSUE TITLE
Question about parts 

### ISSUE THREAD

**Issue by M47H3W** [jmptable/bluetilp#1]
Hello! I know this project was created a long time ago, but I was wondering if I could just get some help with the exact parts I need. So far I have an 8 pin ATtiny85  and an RN-42. I was just wondering what this item in this picture is that I placed an arrow on: https://i.imgur.com/fzeW1Ig.png It appears like it's something that's grouping the wire's but I'm not sure. 
Additionally, would these wires here work? https://www.amazon.com/EDGELEC-Breadboard-Optional-Assorted-Multicolored/dp/B07GD2BWPY/ref=sr_1_3?keywords=Arduino+wires&qid=1570242773&sr=8-3

I apologize about this as I understand this project is no longer active and it's been some years, but unfortunately the whole TI-84 development community died a long time ago and this is the closest thing I found that I could use for a project

**Comment by jmpinit** [comment]
Hi! Sorry it took so long to get back to you.

The component in the image is just a female header, used to group the wires as you guessed. I had soldered male header pins to the attiny so that I could unplug it for programming or testing and then easily plug it back in to the calculator.

The wires that you linked will work fine.

It's cool that you are trying to replicate this old project of mine and I'd be happy to help more if need be. But you will probably get a quicker response from me via email (address should be visible on my profile).
